### ISSUE TITLE
Fatal Exception: java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by vidhipatel94** [jdamcd/android-crop#256]
Fatal Exception: java.lang.UnsupportedOperationException: ExifInterface only supports saving attributes on JPEG formats.
       at android.media.ExifInterface.saveAttributes(ExifInterface.java:1377)
       at com.soundcloud.android.crop.CropUtil.copyExifRotation(CropUtil.java:82)
       at com.soundcloud.android.crop.CropImageActivity.saveOutput(CropImageActivity.java:393)
       at com.soundcloud.android.crop.CropImageActivity.removeLifeCycleListener(CropImageActivity.java:45)
       at com.soundcloud.android.crop.CropImageActivity$5.run(CropImageActivity.java:311)
       at com.soundcloud.android.crop.CropUtil$BackgroundJob.run(CropUtil.java:193)
       at java.lang.Thread.run(Thread.java:818)

**Comment by niravmandani** [comment]
Fatal Exception: java.lang.UnsupportedOperationException: ExifInterface only supports saving attributes on JPEG formats.
       at android.media.ExifInterface.saveAttributes(ExifInterface.java:1377)
       at com.soundcloud.android.crop.CropUtil.copyExifRotation(CropUtil.java:82)
       at com.soundcloud.android.crop.CropImageActivity.saveOutput(CropImageActivity.java:393)
       at com.soundcloud.android.crop.CropImageActivity.access$900(CropImageActivity.java:45)
       at com.soundcloud.android.crop.CropImageActivity$5.run(CropImageActivity.java:311)
       at com.soundcloud.android.crop.CropUtil$BackgroundJob.run(CropUtil.java:193)
       at java.lang.Thread.run(Thread.java:818)

**Comment by TellH** [comment]
+1 . How to fix it ?

**Comment by ritunagpal** [comment]
do you get any solution for this ?

**Comment by niravmandani** [comment]
Not yet
