### ISSUE TITLE
Error reading image: No content provider

### ISSUE THREAD

**Issue by heliujiang** [jdamcd/android-crop#260]
`I have got picture from camere, And the picture is existed!But I can't ...`
![Uploading bug.png…]()
`E/android-crop: Error reading image: No content provider: /storage/emulated/0/casting/pics/1493869338773cover.jpg
                                                                 java.io.FileNotFoundException: No content provider: /storage/emulated/0/casting/pics/1493869338773cover.jpg
                                                                     at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1103)
                                                                     at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:958)
                                                                     at android.content.ContentResolver.openInputStream(ContentResolver.java:683)`

**Comment by heliujiang** [comment]
I solve the problem! Beacuse Uri.parse(Uri.fromFile()) replace Uri.parse(Uri.parse());

**Comment by awaismazharmobilelive** [comment]
Yes, that's the correct approach to handle this scenario.

**Comment by sanjeevda** [comment]
This error is still there in Android 8.0 devices while using camera.
