### ISSUE TITLE
OutOfMemoryError when reading picture.

### ISSUE THREAD

**Issue by jazzeWang** [jdamcd/android-crop#32]
Thanks jdamcd for the source.
there is an issue like the followed:
After choose picture, this happened in reading picture at CropImageActivity at line number : 135. the code is 
rotateBitmap = new RotateBitmap(BitmapFactory.decodeStream(is, null, option), exifRotation);

**Comment by evomer** [comment]
same for me

    --- decoder->decode returned false
01-15 12:19:53.943  23267-23267/app E/android-crop: OOM reading image: null
    java.lang.OutOfMemoryError
            at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
            at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:527)
            at com.soundcloud.android.crop.CropImageActivity.setupFromIntent(CropImageActivity.java:134)
            at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
            at android.app.Activity.performCreate(Activity.java:5254)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1082)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2038)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2099)
            at android.app.ActivityThread.access$600(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4929)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:798)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:565)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by mbaraka** [comment]
Hello, is there any updates about this issue?

**Comment by Nihilus13** [comment]
+1
I think there is some problem with samsung devices(tested on note 2 and s4). First crop, works properly, but the second one throws OOM. The same code tested on Nexus 5 didn't throw an exception after few crops.
