### ISSUE TITLE
OutOfMemoryError  decodeRegion

### ISSUE THREAD

**Issue by btcrecover** [jdamcd/android-crop#33]
croppedImage = decoder.decodeRegion(rect, new BitmapFactory.Options()); 

OutOfMemoryError Exception

**Comment by TiagoGouvea** [comment]
java.lang.OutOfMemoryError
at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:373)
at com.soundcloud.android.crop.CropImageActivity.decodeRegionCrop(CropImageActivity.java:353)
at com.soundcloud.android.crop.CropImageActivity.onSaveClicked(CropImageActivity.java:295)
at com.soundcloud.android.crop.CropImageActivity.access$000(CropImageActivity.java:45)
at com.soundcloud.android.crop.CropImageActivity$3.onClick(CropImageActivity.java:106)
at android.view.View.performClick(View.java:4475)
at android.view.View$PerformClick.run(View.java:18786)
at android.os.Handler.handleCallback(Handler.java:730)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:176)
at android.app.ActivityThread.main(ActivityThread.java:5419)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1046)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:862)
at dalvik.system.NativeStart.main(Native Method)

Using a Galaxy SIII with 1GB Ram.

**Comment by claucookie** [comment]
Same here, up up!

**Comment by shenhuniurou** [comment]
same here， how to do？
