### ISSUE TITLE
FileNotFoundException / Permission denied

### ISSUE THREAD

**Issue by jdamcd** [jdamcd/android-crop#78]
```
java.io.FileNotFoundException: Permission denied
       at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
       at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:617)
       at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:720)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:617)
       at android.content.ContentResolver.openInputStream(ContentResolver.java:452)
       at com.soundcloud.android.crop.CropImageActivity.setupFromIntent(CropImageActivity.java:126)
       at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:75)
       at android.app.Activity.performCreate(Activity.java:5283)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1097)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2209)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2299)
       at android.app.ActivityThread.access$700(ActivityThread.java:150)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1280)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5283)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by slmyldz** [comment]
This crash could be arise uses permission WRITE_EXTERNAL_STORAGE ?
