### ISSUE TITLE
Image failed to decode using GIF decoder

### ISSUE THREAD

**Issue by alexblack** [jdamcd/android-crop#84]
I've seen ~60 instances of this issue among my userbase.  Has anyone else seen this?  I am wondering if my users are trying to crop GIF images, and maybe GIFs are not supported?

```
java.lang.Exception: Crop.RESULT_ERROR from crop: file:///storage/emulated/0/WOInvoice/picture/logo.png
	at com.aadhk.woinvoice.util.LogoUtils.void handleCrop(int,android.content.Intent)(ProGuard:188)
	at com.aadhk.woinvoice.util.LogoUtils.void onActivityResult(int,int,android.content.Intent)(ProGuard:121)
	at com.aadhk.woinvoice.LogoActivity.void onActivityResult(int,int,android.content.Intent)(ProGuard:75)
	at android.app.Activity.dispatchActivityResult(Activity.java:5581)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3517)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3564)
	at android.app.ActivityThread.access$1300(ActivityThread.java:163)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1305)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:157)
	at android.app.ActivityThread.main(ActivityThread.java:5335)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.io.IOException: Image failed to decode using GIF decoder
	at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
	at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:135)
	at com.soundcloud.android.crop.CropImageActivity.android.graphics.Bitmap decodeRegionCrop(android.graphics.Bitmap,android.graphics.Rect)(ProGuard:342)
	at com.soundcloud.android.crop.CropImageActivity.void onSaveClicked()(ProGuard:303)
	at com.soundcloud.android.crop.CropImageActivity.void removeLifeCycleListener(com.soundcloud.android.crop.MonitoredActivity$LifeCycleListener)(ProGuard:45)
                                                  void access$000(com.soundcloud.android.crop.CropImageActivity)
                                                  com.soundcloud.android.crop.HighlightView access$902(com.soundcloud.android.crop.CropImageActivity,com.soundcloud.android.crop.HighlightView)
                                                  void access$1000(com.soundcloud.android.crop.CropImageActivity,android.graphics.Bitmap)
	at com.soundcloud.android.crop.CropImageActivity$3.void onClick(android.view.View)(ProGuard:107)
	at android.view.View.performClick(View.java:4630)
	at android.view.View$PerformClick.run(View.java:19339)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	... 7 more
```

**Comment by mlatu** [comment]
Can confirm that error arise when trying to crop gifs

**Comment by eclair4151** [comment]
yup same issue

**Comment by jdamcd** [comment]
Yeah. GIFs are not supported. The library should handle this and display some warning.

**Comment by jdamcd** [comment]
Closing in favour of https://github.com/jdamcd/android-crop/issues/104 since the caller can check the error and display a message if necessary.

**Comment by landsnail** [comment]
how to fix this bug? or how to crop gif if it only crop the first frame of this gif,any body have a idea ？
