### ISSUE TITLE
Crash when select a image file on google drive

### ISSUE THREAD

**Issue by a642500** [jdamcd/android-crop#95]
“Document” app shipped with the windows system can select image from Google drive. It will cause crash.

```
04-04 23:11:20.666    9940-9940/co.yishun.onemoment.app D/AndroidRuntime﹕ Shutting down VM
04-04 23:11:20.668    9940-9940/co.yishun.onemoment.app E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: co.yishun.onemoment.app, PID: 9940
    java.lang.RuntimeException: Unable to start activity ComponentInfo{co.yishun.onemoment.app/com.soundcloud.android.crop.CropImageActivity}: java.lang.IllegalArgumentException: Unknown column requested: _data
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2340)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2402)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5271)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
     Caused by: java.lang.IllegalArgumentException: Unknown column requested: _data
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:167)
            at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:137)
            at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
            at android.content.ContentResolver.query(ContentResolver.java:478)
            at android.content.ContentResolver.query(ContentResolver.java:422)
            at com.soundcloud.android.crop.CropUtil.getFromMediaUri(CropUtil.java:95)
            at com.soundcloud.android.crop.CropImageActivity.setupFromIntent(CropImageActivity.java:126)
            at com.soundcloud.android.crop.CropImageActivity.onCreate(CropImageActivity.java:79)
            at android.app.Activity.performCreate(Activity.java:5997)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2293)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2402)
            at android.app.ActivityThread.access$900(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1318)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5271)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
04-04 23:14:26.600    9940-9940/co.yishun.onemoment.app I/Process﹕ Sending signal. PID: 9940 SIG: 9
```

**Comment by LukaCiko** [comment]
This issue has already been reported in #47 and fixed in pull request #70. However, the fix has not been published yet. Any updates on that?
